language: emacs-lisp
sudo: required
dist: trusty
cache:
  - directories:
      - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=26.0.90 PRETEST=yes
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=24.2
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.0.91 PRETEST=yes
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
install:
  - cask install
script:
  - cask emacs -Q --batch -l package-lint -f package-lint-current-buffer -f batch-byte-compile counsel-org-clock.el
notifications:
  email:
    on_success: never
    on_failure: always
