# language: emacs-lisp  # No longer allowed https://docs.travis-ci.com/user/languages/
# https://github.com/rolandwalker/emacs-travis/blob/master/.travis.yml#L18
os: linux
dist: focal
cache:
- directories:
  - "$HOME/emacs"
jobs:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  jobs:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
- make setup
install:
- make install
script:
- make test                     # test uncompiled
- make compile                  # test compilation
- make test                     # test compiled
